Repository idris-lang/Idris2, pull requests merged in 2020-06, with the labels that each got.

#238 Fix test reporting when in interactive mode.
  tests/Main.idr
Labels: bug, continuous-integration

#265 In IDE mode, look for a ipkg file before loading
  src/Idris/IDEMode/REPL.idr
  tests/ideMode/ideMode001/dummy.ipkg
  tests/ideMode/ideMode003/dummy.ipkg
Labels: packaging

#272 Use 2^64 constant instead of calculation
  src/Core/Primitives.idr
  tests/chez/chez021/expected
Labels: refactoring

#273 Add a bootstrap from Idris 1 CI script
  .github/workflows/ci-full-bootstrap.yml
Labels: continuous-integration

#275 [ re #270 ] Mention the target type of the auto search
  src/Core/AutoSearch.idr
  src/Core/Core.idr
  src/Idris/Error.idr
  tests/Main.idr
  tests/idris2/error004/expected
  tests/idris2/interface015/expected
  tests/idris2/interface015/gnu.idr
  tests/idris2/interface016/TwoNum.idr
  tests/idris2/interface016/expected
  tests/idris2/interface016/run
Labels: auto-implicit

#256 "--repl" command for opening a REPL in a package
  src/Idris/Main.idr
  src/Idris/Package.idr
  tests/Main.idr
  tests/idris2/pkg004/Dummy.idr
  tests/idris2/pkg004/dummy.ipkg
  tests/idris2/pkg004/expected
  tests/idris2/pkg004/input
  tests/idris2/pkg004/run
Labels: packaging, repl

#334 Make reference and source agree about literate markdown
  docs/source/reference/literate.rst
  src/Parser/Unlit.idr
Labels: Confirmed bug, documentation, language: literate

#309 Add 'optional' command line options
  CHANGELOG.md
  src/Idris/CommandLine.idr
Labels: cli: options

#322 Function mapping `Not (x=True)` to `x=False` was added for `Bool`s
  libs/base/Data/Bool.idr
  tests/idris2/coverage010/expected
Labels: enhancement, library: base

#332 VMCODE: Carry over required type names for named constructors without a tag
  src/Compiler/VMCode.idr
Labels: implem: vm

#347 reduce sugar in confusing error messages
  src/Idris/Resugar.idr
  tests/idris2/with003/expected
Labels: error: bad message, implem: pretty printing

#348 change namespace parser to have minimum indentation
  src/Idris/Parser.idr
  tests/Main.idr
  tests/idris2/namespace001/Dup.idr
  tests/idris2/namespace001/Scope.idr
  tests/idris2/namespace001/expected
  tests/idris2/namespace001/run
Labels: Confirmed bug, language: namespace

#344 Updated documentation for export
  docs/source/tutorial/modules.rst
Labels: documentation

#355 Format Homebrew install code block
  docs/source/tutorial/starting.rst
Labels: typo

#352 Extract modules from Prelude
  libs/prelude/Prelude.idr
  libs/prelude/Prelude/Basics.idr
  libs/prelude/Prelude/Uninhabited.idr
  libs/prelude/prelude.ipkg
  tests/ideMode/ideMode001/expected
  tests/ideMode/ideMode003/expected
Labels: library: prelude, refactoring

#357 Update linear.rst
  docs/source/app/linear.rst
Labels: typo

#389 List's `snoc` injectivity property was renamed approporiately.
  libs/contrib/Data/List/Equalities.idr
  libs/contrib/Data/List/Palindrome.idr
Labels: Confirmed bug, naming

#333 Make Data.Vect linear
  libs/base/Data/Vect.idr
  tests/idris2/coverage010/expected
Labels: enhancement, library: base
