Repository idris-lang/Idris2, pull requests merged in 2021-12, with the labels that each got.

#2174 [ cleanup ] lift quoteX patterns to toplevel
  src/Core/SchemeEval/Evaluate.idr
Labels: code: cleanup, implem: scheme eval, event: IDM 2021/12

#2173 [ fix #2098 ] Allow unclosed comment blocks
  src/Libraries/Text/Lexer/Core.idr
  src/Parser/Lexer/Source.idr
  tests/Main.idr
  tests/idris2/basic066/comment.idr
  tests/idris2/basic066/expected
  tests/idris2/basic066/run
  tests/idris2/basic067/expected
  tests/idris2/basic067/input
  tests/idris2/basic067/run
  tests/idris2/basic067/unclosed1.idr
  tests/idris2/basic067/unclosed2.idr
  tests/idris2/basic067/unclosed3.idr
Labels: event: IDM 2021/12

#2182 [ fix ] highlighting 'as' & 'off' keywords
  src/Idris/Parser.idr
Labels: status: confirmed bug, ide: highlighting, event: IDM 2021/12

#2184 [ fix ] Re-add Pretty instances for IntX
  libs/contrib/Text/PrettyPrint/Prettyprinter/Doc.idr
Labels: library: contrib, language: builtin

#2179 [ fix #1404 ] Totality annotation for data type definitions
  libs/base/Language/Reflection/TTImp.idr
  src/Core/Binary.idr
  src/Idris/Desugar.idr
  src/Idris/Desugar/Mutual.idr
  src/Idris/Elab/Interface.idr
  src/Idris/Parser.idr
  src/Idris/Resugar.idr
  src/Idris/Syntax.idr
  src/TTImp/Elab/Local.idr
  src/TTImp/Elab/Quote.idr
  src/TTImp/Parser.idr
  src/TTImp/ProcessData.idr
  src/TTImp/ProcessDecls.idr
  src/TTImp/ProcessRecord.idr
  src/TTImp/Reflect.idr
  src/TTImp/TTImp.idr
  src/TTImp/TTImp/Functor.idr
  src/TTImp/Utils.idr
  tests/Main.idr
  tests/idris2/record014/Issue1404.idr
  tests/idris2/record014/expected
  tests/idris2/record014/run
  tests/idris2/reflection004/refdecl.idr
  tests/idris2/reflection014/expected
  tests/idris2/reflection014/input
  tests/idris2/reflection014/refdecl.idr
  tests/idris2/reflection014/run
  tests/idris2/total013/Issue1404.idr
  tests/idris2/total013/expected
  tests/idris2/total013/run
Labels: event: IDM 2021/12

#2181 [ fix #2138] Add an %unhide pragma
  src/Core/Context.idr
  src/Idris/Desugar.idr
  src/Idris/Parser.idr
  src/Idris/Syntax.idr
  tests/Main.idr
  tests/idris2/basic068/Issue2138.idr
  tests/idris2/basic068/expected
  tests/idris2/basic068/run
Labels: implem: scope, event: IDM 2021/12

#2185 Fix compilation on OpenBSD
  support/c/idris_file.c
Labels: event: IDM 2021/12

#2189 [ fix #2032 ] Slow typechecking on `Int` operation when `Data.Fin.fromInteger` is in scope
  libs/base/Data/Fin.idr
  tests/base/data_fin001/expected
  tests/base/data_fin001/fromInteger.idr
  tests/base/data_fin001/run
  tests/idris2/basic042/expected
Labels: performance, library: base, event: IDM 2021/12

#2186 [ fix ] isImplicit now works for all binders
  src/Core/TT.idr
Labels: event: IDM 2021/12

#2199 [ cleanup ] using whenJust in Driver
  src/Idris/Driver.idr
Labels: code: cleanup

#2198 Rename `lp/loadpackage` to `package`
  CHANGELOG.md
  src/Idris/Parser.idr
Labels: cli: repl, breaking

#2171 [ refactor ] IDE protocol as a separate module hierarchy
  idris2api.ipkg
  idris2protocols.ipkg.hide
  src/Compiler/ES/Codegen.idr
  src/Compiler/RefC/RefC.idr
  src/Compiler/Scheme/Chez.idr
  src/Compiler/Scheme/Gambit.idr
  src/Compiler/Scheme/Racket.idr
  src/Core/Metadata.idr
  src/Core/Name/Namespace.idr
  src/Idris/IDEMode/Commands.idr
  src/Idris/IDEMode/Holes.idr
  src/Idris/IDEMode/Pretty.idr
  src/Idris/IDEMode/REPL.idr
  src/Idris/IDEMode/SyntaxHighlight.idr
  src/Idris/REPL/Common.idr
  src/Libraries/Data/Span.idr
  src/Libraries/Text/Bounded.idr
  src/Libraries/Text/PrettyPrint/Prettyprinter/Doc.idr
  src/Parser/Lexer/Source.idr
  src/Protocol/Hex.idr
  src/Protocol/IDE.idr
  src/Protocol/IDE/Command.idr
  src/Protocol/IDE/Decoration.idr
  src/Protocol/IDE/FileContext.idr
  src/Protocol/IDE/Formatting.idr
  src/Protocol/IDE/Highlight.idr
  src/Protocol/IDE/Holes.idr
  src/Protocol/IDE/Result.idr
  src/Protocol/SExp.idr
  src/TTImp/PartialEval.idr
  tests/ideMode/ideMode001/expected
  tests/ideMode/ideMode002/expected.in
  tests/ideMode/ideMode003/expected
  tests/ideMode/ideMode004/expected
  tests/ideMode/ideMode005/expected1
  tests/ideMode/ideMode005/expected2
  tests/ideMode/ideMode005/expected3
  tests/ideMode/ideMode005/expected4
  tests/ideMode/ideMode005/expected5
  tests/ideMode/ideMode005/expected6
  tests/ideMode/ideMode005/expected7
  tests/ideMode/ideMode005/expected8
  tests/ideMode/ideMode005/expected9
  tests/ideMode/ideMode005/expectedA
  tests/ideMode/ideMode005/expectedB
  tests/ideMode/ideMode005/expectedC
  tests/ideMode/ideMode005/expectedD
  tests/ideMode/ideMode005/expectedE
  tests/ideMode/ideMode005/expectedF
  tests/ideMode/ideMode005/expectedG
  tests/ideMode/ideMode005/expectedH
Labels: code: refactoring, cli: ide-mode, event: IDM 2021/12

#2119 [ re #238 ] Fix program error condition of `git diff` call in `Golden`
  libs/test/Test/Golden.idr
  support/c/idris_system.c
Labels: library: test

#2231 [cleanup] Small round of unused import culling.
  libs/base/System/Escape.idr
  libs/contrib/Search/Generator.idr
  libs/network/Network/Socket.idr
  libs/test/Test/Golden.idr
  src/Compiler/RefC/CC.idr
  src/Idris/IDEMode/Parser.idr
  src/Idris/IDEMode/SyntaxHighlight.idr
  src/Idris/ProcessIdr.idr
  src/Protocol/IDE.idr
  src/Protocol/IDE/Formatting.idr
  src/TTImp/Parser.idr
Labels: code: cleanup

#2234 Add 'tryParse' function to 'System.Path'
  libs/contrib/System/Path.idr
Labels: enhancement, library: contrib

#2232 [ nix ] fix bitrot
  nix/package.nix
Labels: admin: packaging, os: nix
