Repository idris-lang/Idris2, pull requests merged in 2021-10, with the labels that each got.

#1942 Warn about unreachable default clauses
  idris2api.ipkg
  src/Compiler/CompileExpr.idr
  src/Compiler/RefC/RefC.idr
  src/Core/Binary.idr
  src/Core/Case/CaseBuilder.idr
  src/Core/Case/CaseTree.idr
  src/Core/Case/Util.idr
  src/Core/Context.idr
  src/Core/Context/Context.idr
  src/Core/Coverage.idr
  src/Core/GetType.idr
  src/Core/Hash.idr
  src/Core/LinearCheck.idr
  src/Core/Normalise.idr
  src/Core/Normalise/Convert.idr
  src/Core/Normalise/Eval.idr
  src/Core/Normalise/Quote.idr
  src/Core/SchemeEval/Compile.idr
  src/Core/TTC.idr
  src/Core/Termination.idr
  src/Core/Unify.idr
  src/Core/UnifyState.idr
  src/Idris/Error.idr
  src/Idris/REPL.idr
  src/Idris/REPL/FuzzySearch.idr
  src/Libraries/Data/SortedSet.idr
  src/TTImp/Elab/App.idr
  src/TTImp/Elab/Case.idr
  src/TTImp/Elab/Delayed.idr
  src/TTImp/Elab/ImplicitBind.idr
  src/TTImp/Elab/Local.idr
  src/TTImp/Elab/Utils.idr
  src/TTImp/Interactive/ExprSearch.idr
  src/TTImp/PartialEval.idr
  src/TTImp/ProcessBuiltin.idr
  src/TTImp/ProcessDef.idr
  src/TTImp/Unelab.idr
  tests/Main.idr
  tests/chez/chez020/Popen.idr
  tests/idris2/casetree002/DefaultCases.idr
  tests/idris2/casetree002/Issue1079.idr
  tests/idris2/casetree002/expected
  tests/idris2/casetree002/run
Labels: enhancement, safety: coverage, implem: pattern-matching, error: warning

#1968 print location of implicit name shadowing with the warning.
  src/Idris/Error.idr
  tests/idris2/basic049/expected
  tests/idris2/coverage015/expected
  tests/idris2/interface008/expected
  tests/idris2/real001/expected
  tests/idris2/real002/expected
  tests/idris2/reflection006/expected
  tests/idris2/warning001/expected
  tests/typedd-book/chapter03/expected
  tests/typedd-book/chapter04/expected
  tests/typedd-book/chapter06/expected
  tests/typedd-book/chapter07/expected
  tests/typedd-book/chapter08/expected
  tests/typedd-book/chapter11/expected
  tests/typedd-book/chapter12/expected
  tests/typedd-book/chapter14/expected
Labels: error: warning

#1961 [tests] fix idris2/pk010: make it more roboust
  tests/idris2/pkg010/gen_expected.sh
  tests/idris2/pkg010/run
Labels: admin: continuous-integration

#1966 Backend cookbook rst and typo fixes
  docs/source/backends/backend-cookbook.rst
Labels: documentation, typo

#1960 [build] fix install-libs target
  Makefile
Labels: status: confirmed bug, admin: installation, implem: incremental compilation
