Repository idris-lang/Idris2, pull requests merged in 2023-11, with the labels that each got.

#3131 [ doc ] Headings for envvars based on use
  CHANGELOG.md
  docs/source/reference/envvars.rst
Labels: documentation, enhancement

#3135 Support "make -j"
  CHANGELOG.md
  Makefile
Labels: enhancement, status: info needed, admin: installation

#3138 Cleanup of `sizeEq`
  src/Core/Termination/CallGraph.idr
Labels: code: cleanup

#3116 [ base ] Add bindings for ieee `Double` number consts
  CHANGELOG.md
  libs/base/Data/Double.idr
  libs/base/base.ipkg
  src/Compiler/Scheme/Racket.idr
  support/chez/support.ss
  support/racket/support.rkt
  tests/allschemes/double001/URandEpsilon.idr
  tests/allschemes/double001/expected
  tests/allschemes/double001/input
  tests/allschemes/double001/run
  tests/allschemes/double002/NaN.idr
  tests/allschemes/double002/expected
  tests/allschemes/double002/input
  tests/allschemes/double002/run
  tests/allschemes/double003/Inf.idr
  tests/allschemes/double003/expected
  tests/allschemes/double003/input
  tests/allschemes/double003/run
  tests/node/double001/URandEpsilon.idr
  tests/node/double001/expected
  tests/node/double001/input
  tests/node/double001/run
  tests/node/double002/NaN.idr
  tests/node/double002/expected
  tests/node/double002/input
  tests/node/double002/run
  tests/node/double003/Inf.idr
  tests/node/double003/expected
  tests/node/double003/input
  tests/node/double003/run
Labels: enhancement, library: base, language: float

#2669 refactor README and installation instructions
  INSTALL.md
  README.md
  docs/source/backends/javascript.rst
Labels: documentation, enhancement

#3147 [ cleanup ] remove dead code MkSeqConstraint
  src/Core/Unify.idr
  src/Core/UnifyState.idr
Labels: code: cleanup

#3154 [ fix #3103, #3104 ] Disable broken tests
  tests/Main.idr
  tests/racket/conditions006/Main.idr
  tests/racket/conditions007/Main.idr
Labels: status: confirmed bug, admin: continuous-integration
