Repository idris-lang/Idris2, pull requests merged in 2023-06, with the labels that each got.

#2984 Ignore `UseSide` annotation in non-linear as-patterns
  src/TTImp/ProcessDef.idr
  tests/Main.idr
  tests/idris2/linear017/As.idr
  tests/idris2/linear017/expected
  tests/idris2/linear017/run
Labels: language: quantity, language: as-pattern

#2970 Typos: Run 'typos -w' command over docs/
  docs/source/backends/javascript.rst
  docs/source/backends/libraries.rst
  docs/source/reference/builtins.rst
  docs/source/reference/packages.rst
  docs/source/reference/strings.rst
  docs/source/tutorial/typesfuns.rst
  docs/source/typedd/typedd.rst
  docs/source/updates/updates.rst
  libs/papers/Language/IntrinsicScoping/TypeTheory.idr
  libs/papers/Language/TypeTheory.idr
Labels: typo

#2997 Infix namespace hiding
  CHANGELOG.md
  docs/source/reference/pragmas.rst
  src/Compiler/ES/Doc.idr
  src/Core/Name.idr
  src/Idris/Desugar.idr
  src/Idris/Doc/String.idr
  src/Idris/Parser.idr
  src/Idris/Resugar.idr
  src/Idris/Syntax.idr
  src/Idris/Syntax/TTC.idr
  src/Libraries/Data/ANameMap.idr
  src/Libraries/Data/StringMap.idr
  src/Parser/Lexer/Source.idr
  src/Parser/Rule/Source.idr
  tests/Main.idr
  tests/codegen/con001/expected
  tests/idris2/basic044/expected
  tests/idris2/interactive030/expected
  tests/idris2/namespace005/Lib1.idr
  tests/idris2/namespace005/Lib2.idr
  tests/idris2/namespace005/LibPre1.idr
  tests/idris2/namespace005/LibPre2.idr
  tests/idris2/namespace005/Main0.idr
  tests/idris2/namespace005/Main1.idr
  tests/idris2/namespace005/Main3.idr
  tests/idris2/namespace005/MainConflict.idr
  tests/idris2/namespace005/MainFail.idr
  tests/idris2/namespace005/MainPre0.idr
  tests/idris2/namespace005/MainPre1.idr
  tests/idris2/namespace005/NonConflict1.idr
  tests/idris2/namespace005/NonConflict2.idr
  tests/idris2/namespace005/expected
  tests/idris2/namespace005/run
  tests/idris2/record019/expected
  tests/idris2/spec001/expected
  tests/idris2/warning004/expected
Labels: language: namespace, syntax, language: fixity

#2918 [ new ] Add generalisations of `min` and `max` for `StronglyConnex`
  CHANGELOG.md
  libs/base/Control/Order.idr
Labels: enhancement, library: base

#3004 [ fix ] Fix issue with eager evaluation of crashing functions (fixes #3003)
  src/Compiler/Opts/ToplevelConstants.idr
  tests/Main.idr
  tests/chez/chez036/Crash.idr
  tests/chez/chez036/Crash2.idr
  tests/chez/chez036/Crash3.idr
  tests/chez/chez036/expected
  tests/chez/chez036/run
Labels: status: confirmed bug
