Repository idris-lang/Idris2, pull requests merged in 2025-08, with the labels that each got.

#3585 [ admin ] Finish releasing 0.7.0, clear the release checklist
  Release/CHECKLIST
Labels: admin: meta

#3608 [ fix ] the dropConAlt case was dropping the protected inner
  src/Compiler/Opts/CSE.idr
Labels: status: confirmed bug, code: refactoring, implem: common subexpression elimination

#3607 [ re #3603 ] Actually bother introducing VarSet
  .github/workflows/ci-idris2-and-libs.yml
  idris2api.ipkg
  src/Compiler/CompileExpr.idr
  src/Compiler/LambdaLift.idr
  src/Compiler/Opts/ConstantFold.idr
  src/Compiler/Opts/Identity.idr
  src/Core/Env.idr
  src/Core/LinearCheck.idr
  src/Core/Normalise/Convert.idr
  src/Core/Normalise/Quote.idr
  src/Core/SchemeEval/Quote.idr
  src/Core/TT/Var.idr
  src/Core/Unify.idr
  src/Libraries/Data/NatSet.idr
  src/Libraries/Data/VarSet.idr
  src/Libraries/Data/VarSet/Core.idr
  src/TTImp/Elab/App.idr
  src/TTImp/Elab/Case.idr
  src/TTImp/Elab/Check.idr
  src/TTImp/Elab/ImplicitBind.idr
  src/TTImp/Elab/Utils.idr
  src/TTImp/PartialEval.idr
  src/TTImp/Unelab.idr
Labels: code: refactoring

#3599 Unify binder data types using WithData
  src/Core/Core.idr
  src/Core/TT/Binder.idr
  src/Core/TTC.idr
  src/Core/WithData.idr
  src/Idris/Desugar.idr
  src/Idris/Desugar/Mutual.idr
  src/Idris/Elab/Implementation.idr
  src/Idris/Parser.idr
  src/Idris/Resugar.idr
  src/Idris/Syntax.idr
  src/Idris/Syntax/Traversals.idr
  src/Libraries/Data/WithData.idr
  src/TTImp/Elab/Local.idr
  src/TTImp/Elab/Quote.idr
  src/TTImp/Parser.idr
  src/TTImp/ProcessParams.idr
  src/TTImp/ProcessRecord.idr
  src/TTImp/Reflect.idr
  src/TTImp/TTImp.idr
  src/TTImp/TTImp/Functor.idr
  src/TTImp/TTImp/TTC.idr
  src/TTImp/TTImp/Traversals.idr
  src/TTImp/Utils.idr
Labels: code: refactoring, syntax

#3579 Grammar improvements to the beginning of the tutorial
  docs/source/tutorial/interfaces.rst
  docs/source/tutorial/starting.rst
  docs/source/tutorial/typesfuns.rst
  docs/source/tutorial/windows.rst
Labels: documentation

#3621 remove now-unneeded and no longer supported overrideSDK calls from Nix files
  flake.lock
  flake.nix
  nix/support.nix
Labels: admin: packaging, os: nix
